server:
  port: 8083

populate:
  list:
    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=835547&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1591-0.015-澜磷,
    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=857652&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-60-0.01-墨岩,
    #    https://api.youpin898.com/api/market/goods/sell_order?game=csgo&goods_id=857652&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-60-0.01-墨岩,
    #    https://www.igxe.cn/product/trade/730/614390-1300-0.3-短剑无涂装,
    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=759509&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1300-0.3-短剑无涂装,
    #    https://www.c5game.com/gw/steamtrade/sga/sell/v1/list?itemId=553479077&delivery=0&bargain=0&levelName=&slotStickerIds=&sort=0&paintSeed=&page=1&containSticker=&reqId=16515552436009150571-1300-0.3-短剑无涂装,
    #    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-1300-0.3-短剑无涂装-2791,
    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=33915&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-8101-0.51-水栽竹,
    #    https://www.igxe.cn/product/trade/730/25744-8101-0.51-水栽竹,
    #    https://www.c5game.com/gw/steamtrade/sga/sell/v1/list?itemId=26422&delivery=0&bargain=0&levelName=&slotStickerIds=&sort=0&paintSeed=&page=1&containSticker=&reqId=16518585540068942504-8101-0.51-水栽竹,
    #    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-8101-0.51-水栽竹-43800

    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=835780&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1590-0.04-印花集,
    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=34099&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-2100-0.07-雷击AWP,
    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=887070&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1000-0.01-夜愿,
    #    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=835907&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-3201-0.14-警告,
    #
    #    https://www.c5game.com/gw/steamtrade/sga/sell/v1/list?itemId=808857281272217600&delivery=0&bargain=0&levelName=&slotStickerIds=&sort=0&paintSeed=&page=1&containSticker=&reqId=16515474517881763992-1560-0.01-印花集,
    #    https://www.c5game.com/gw/steamtrade/sga/sell/v1/list?itemId=809585869123747840&delivery=0&bargain=0&levelName=&slotStickerIds=&sort=0&paintSeed=&page=1&containSticker=&reqId=16516379193525335462-3300-0.08-警告,
    #    https://www.c5game.com/gw/steamtrade/sga/sell/v1/list?itemId=958661081649799168&delivery=0&bargain=0&levelName=&slotStickerIds=&sort=0&paintSeed=&page=1&containSticker=&reqId=16515551834791458966-1000-0.01-夜愿,
    #
    #    https://www.igxe.cn/product/trade/730/658899-1500-0.04-印花集,
    #    https://www.igxe.cn/product/trade/730/666915-1000-0.04-夜愿,
    #    https://www.igxe.cn/product/trade/730/3880-2100-0.07-雷击AWP,
    #    https://www.igxe.cn/product/trade/730/658733-3201-0.145-警告,
    #
    #    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-2100-0.07-雷击AWP-43393,
    #    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-1000-0.04-夜愿-101544,
    #    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-1590-0.04-印花集-46298,
    #    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-3201-0.14-警告-51909

    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=887070&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1000-0.01-夜愿,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=33969&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-480-0.01-皇后,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=835826&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1480-0.01-美洲豹,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=835780&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1560-0.01-印花集,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=835547&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-1545-0.01-澜磷,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=42181&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-865-0.01-枪响人亡,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=35063&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-380-0.01-暮光星系,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=871769&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-10350-0.01-黄金藤蔓,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=835907&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-3300-0.08-警告,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=422813&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-5300-0.08-钴蓝骷髅,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=45605&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-2870-0.08-套印,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=45581&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-2160-0.08-玳瑁,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=45440&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-8900-0.08-双栖,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=45486&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-10000-0.08-王蛇,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=836089&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-9200-0.08-雪豹,
    https://buff.163.com/api/market/goods/sell_order?game=csgo&goods_id=836016&page_num=1&sort_by=default&mode=&allow_tradable_cooldown=1-6200-0.08-一线特工,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-1000-0.01-夜愿-101544,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-480-0.01-皇后-43397,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-1480-0.01-美洲豹-46962,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-1560-0.01-印花集-46298,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-1545-0.01-澜磷-45056,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-865-0.01-枪响人亡-43639,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-380-0.01-暮光星系-45603,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-10350-0.01-黄金藤蔓-62217,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-3300-0.08-警告-51909,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-5300-0.08-钴蓝骷髅-43525,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-2870-0.08-套印-44630,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-2160-0.08-玳瑁-51990,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-8900-0.08-双栖-47079,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-10000-0.08-王蛇-51814,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-9200-0.08-雪豹-52820,
    https://api.youpin898.com/api/homepage/es/commodity/GetCsGoPagedList-6200-0.08-一线特工-48145,
    https://www.igxe.cn/product/trade/730/666915-1000-0.01-夜愿,
    https://www.igxe.cn/product/trade/730/605338-480-0.01-皇后,
    https://www.igxe.cn/product/trade/730/659091-1480-0.01-美洲豹,
    https://www.igxe.cn/product/trade/730/658899-1560-0.01-印花集,
    https://www.igxe.cn/product/trade/730/658805-1545-0.01-澜磷,
    https://www.igxe.cn/product/trade/730/660430-865-0.01-枪响人亡,
    https://www.igxe.cn/product/trade/730/6462-380-0.01-暮光星系,
    https://www.igxe.cn/product/trade/730/664259-10350-0.01-黄金藤蔓,
    https://www.igxe.cn/product/trade/730/658733-3300-0.08-警告,
    https://www.igxe.cn/product/trade/730/610763-5300-0.08-钴蓝骷髅,
    https://www.igxe.cn/product/trade/730/611010-2870-0.08-套印,
    https://www.igxe.cn/product/trade/730/610904-2160-0.08-玳瑁,
    https://www.igxe.cn/product/trade/730/610901-8900-0.08-双栖,
    https://www.igxe.cn/product/trade/730/611017-10000-0.08-王蛇,
    https://www.igxe.cn/product/trade/730/658991-9200-0.08-雪豹,
    https://www.igxe.cn/product/trade/730/659204-6200-0.08-一线特工

#平台接口:
#  buff: buff.163.com/api/market/goods/sell_order
#  c5: www.c5game.com/gw/steamtrade/sga/sell/v1/list
#  igex: www.igxe.cn/product/trade/